### ISSUE TITLE
river_shape

### ISSUE THREAD

**Issue by zhaowentong** [damianobaldan/riverconn_tutorial#1]
How do I get the "Up_cell"?River shapes obtained from HydroSHEDS do not have this field.

**Comment by damianobaldan** [comment]
This is a problem with HydroRIVERS versions. The field UP_CELLS (number of upstream cells) was in v1.0, that I used for the tutorial, probably you are using version v1.1, which has different fields, see the HydroSHEDS and HydroRIVERS technical documentation available at:[ https://www.hydrosheds.org/products/hydrorivers](https://www.hydrosheds.org/products/hydrorivers). That command was introdiced to prune the shapefile to have manageable network sizes. In the new HydroRIVERS there's some attributes that could be used to this end, e.g. ORD_STRA, ORD_CLAS, ORD_FLOW.

**Comment by damianobaldan** [comment]
> How do I get the "Up_cell"?River shapes obtained from HydroSHEDS do not have this field.

This is a problem with HydroRIVERS versions. The field UP_CELLS (number of upstream cells) was in v1.0, that I used for the tutorial, probably you are using version v1.1, which has different fields, see the HydroSHEDS and HydroRIVERS technical documentation available at:[ https://www.hydrosheds.org/products/hydrorivers](https://www.hydrosheds.org/products/hydrorivers). That command was introdiced to prune the shapefile to have manageable network sizes. In the new HydroRIVERS there's some attributes that could be used to this end, e.g. ORD_STRA, ORD_CLAS, ORD_FLOW.

**Comment by zhaowentong** [comment]
Thank you very much for your answer to the last question, which is very helpful to me. However, the following error occurred when I was running the code. The code before this can run successfully.
'''
>outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)
>outlet
#[1] 1
> river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)
#Error in create_network(network_links, river_net_simplified, outlet, TRUE) :unused argument (TRUE)
'''
After thinking for some time, I still can't find a solution, so I would like to ask for your advice. If you can give some  advice, I would be very grateful.

**Comment by damianobaldan** [comment]
> Thank you very much for your answer to the last question, which is very helpful to me. However, the following error occurred when I was running the code. The code before this can run successfully. '''
> 
> > outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)
> > outlet
> > #[1] 1
> > river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)
> > #Error in create_network(network_links, river_net_simplified, outlet, TRUE) :unused argument (TRUE)
> > '''
> > After thinking for some time, I still can't find a solution, so I would like to ask for your advice. If you can give some  advice, I would be very grateful.

Usually this error occours when the river shapefile has unnecessary fields with names that are similar. Try removing all column that are not needed with dplyr::select. To help me identifying the error, please provide a minimal reproducible example.

**Comment by zhaowentong** [comment]
Hello, the river shapefile I used has only one field, but the above problems still occur after running the code, so I would like to ask for your help. I have selected some data for running the code as an example, and the code and data can be seen in the appendix file.
[data and code.zip](https://github.com/damianobaldan/riverconn_tutorial/files/10661665/data.and.code.zip)



At 2023-02-06 15:45:15, "Damiano Baldan" ***@***.***> wrote:

Thank you very much for your answer to the last question, which is very helpful to me. However, the following error occurred when I was running the code. The code before this can run successfully. '''

outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)
outlet
#[1] 1
river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)
#Error in create_network(network_links, river_net_simplified, outlet, TRUE) :unused argument (TRUE)
'''
After thinking for some time, I still can't find a solution, so I would like to ask for your advice. If you can give some advice, I would be very grateful.

Usually this error occours when the river shapefile has unnecessary fields with names that are similar. Try removing all column that are not needed with dplyr::select. To help me identifying the error, please provide a minimal reproducible example.

**Comment by damianobaldan** [comment]
The problem with your data is the presence of multiple confluences. There
is a mistake in the tutorial, the multiple_confluence function should be
called on the river_net_simplified object to return the proper position of
'problematic' confluences. I will update the tutorial in this regard, for
now just call multiple_confluences(river_net_simplified) right before
calling the network_creation function. Then you will have the positions in
your shapefile where 4 segments intersect (problematic confluence) and you
can manually edit your shapefile in arcgis or qgis by removing one of the
four segments (usually it's very small and it might be just an HydroRIVERS
artifact).

Il giorno lun 6 feb 2023 alle ore 10:36 zhaowentong <
***@***.***> ha scritto:

>
>
>
> Hello, the river shapefile I used has only one field, but the above
> problems still occur after running the code, so I would like to ask for
> your help. I have selected some data for running the code as an example,
> and the code and data can be seen in the appendix file.
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by zhaowentong** [comment]
Thank you for your answer very much,the question has been solved.

**Comment by zhaowentong** [comment]
Excuse me, I used HydroSHEDS v1.1 and modified the river section to make the junction point less than 4, but this error still occurred when I was running, it worked normally when I used HydroSHEDS v1.0. I tried to run creat_network, and found that the calculation result of delta was NAN after running. I don't know how to solve it, so I want to ask for help! Here is the modified code and data.

'''
river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)

#Error in create_network(network_links, river_net_simplified, outlet, TRUE) : unused argument (TRUE)

'''










At 2023-02-06 17:36:26, "赵文通" ***@***.***> wrote:




Hello, the river shapefile I used has only one field, but the above problems still occur after running the code, so I would like to ask for your help. I have selected some data for running the code as an example, and the code and data can be seen in the appendix file.













At 2023-02-06 15:45:15, "Damiano Baldan" ***@***.***> wrote:

Thank you very much for your answer to the last question, which is very helpful to me. However, the following error occurred when I was running the code. The code before this can run successfully. '''

outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)
outlet
#[1] 1
river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)
#Error in create_network(network_links, river_net_simplified, outlet, TRUE) :unused argument (TRUE)
'''
After thinking for some time, I still can't find a solution, so I would like to ask for your advice. If you can give some advice, I would be very grateful.

Usually this error occours when the river shapefile has unnecessary fields with names that are similar. Try removing all column that are not needed with dplyr::select. To help me identifying the error, please provide a minimal reproducible example.

**Comment by damianobaldan** [comment]
Send me a minimal reproducible example.
Damiano

Il giorno lun 13 feb 2023 alle ore 14:33 zhaowentong <
***@***.***> ha scritto:

> Excuse me, I used HydroSHEDS v1.1 and modified the river section to make
> the junction point less than 4, but this error still occurred when I was
> running, it worked normally when I used HydroSHEDS v1.0. I tried to run
> creat_network, and found that the calculation result of delta was NAN after
> running. I don't know how to solve it, so I want to ask for help! Here is
> the modified code and data.
>
> '''
> river_graph <- create_network(network_links,
> river_net_simplified,outlet,TRUE)
>
> #Error in create_network(network_links, river_net_simplified, outlet,
> TRUE) : unused argument (TRUE)
>
> '''
>
>
>
>
>
>
>
>
>
>

**Comment by zhaowentong** [comment]
This is an exmaple.
[code and data.zip](https://github.com/damianobaldan/riverconn_tutorial/files/10722823/code.and.data.zip)

**Comment by zhaowentong** [comment]
See the attachment for a case.
[code and data.zip](https://github.com/damianobaldan/riverconn_tutorial/files/10727956/code.and.data.zip)





At 2023-02-13 21:33:07, "赵文通" ***@***.***> wrote:

Excuse me, I used HydroSHEDS v1.1 and modified the river section to make the junction point less than 4, but this error still occurred when I was running, it worked normally when I used HydroSHEDS v1.0. I tried to run creat_network, and found that the calculation result of delta was NAN after running. I don't know how to solve it, so I want to ask for help! Here is the modified code and data.

'''
river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)

#Error in create_network(network_links, river_net_simplified, outlet, TRUE) : unused argument (TRUE)

'''









At 2023-02-06 17:36:26, "赵文通" ***@***.***> wrote:




Hello, the river shapefile I used has only one field, but the above problems still occur after running the code, so I would like to ask for your help. I have selected some data for running the code as an example, and the code and data can be seen in the appendix file.













At 2023-02-06 15:45:15, "Damiano Baldan" ***@***.***> wrote:

Thank you very much for your answer to the last question, which is very helpful to me. However, the following error occurred when I was running the code. The code before this can run successfully. '''

outlet <- get_outlet(river_net_simplified, shape_basin, distance = 1)
outlet
#[1] 1
river_graph <- create_network(network_links, river_net_simplified,outlet,TRUE)
#Error in create_network(network_links, river_net_simplified, outlet, TRUE) :unused argument (TRUE)
'''
After thinking for some time, I still can't find a solution, so I would like to ask for your advice. If you can give some advice, I would be very grateful.

Usually this error occours when the river shapefile has unnecessary fields with names that are similar. Try removing all column that are not needed with dplyr::select. To help me identifying the error, please provide a minimal reproducible example.

**Comment by damianobaldan** [comment]
Hi,

It's a problem with HydroSHEDS data, it looks like there are some adjacent
segments of the shapefile that do not overlap perfectly.
To spot where they are you can use the river_temp object created internally
in the network_creation function:
1) call the igraph::memberships function: clusters <-
memberships(river_temp)$membership
2) add the cluster information to the shapefile
3) save the shapefile
4) check the position of the segments in qgis and correct manually

I will work on a function to identify this issue and I will add it to the
tutorial.

Best,
Damiano

Il giorno mar 14 feb 2023 alle ore 03:05 zhaowentong <
***@***.***> ha scritto:

>
>
>
> See the attachment for a case.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by damianobaldan** [comment]
A function like this should do the job. It will be incorporated in the
tutorial. Best, Damiano

#' Detects gaps in the river network polyline that might cause the function
network_creation to fail
#'
#' @param shape the river network shapefile to be used as input to the
network_creation function
#'
#' @return a point shapefile with the position of the gaps in the river
network
#'
gaps_detection <- function(shape){

  # Break shapefile at points
  river_to_points <- shape %>%
    st_as_sf %>%
    st_cast("POINT") %>%
    mutate(id = 1:nrow(.))

  # Retain all confluences, both good and 'broken' ones
  joins_selection <- river_to_points %>%
    st_is_within_distance(dist = 0.0001) %>%
    Filter(function(x){length(x) > 2 }, .) %>%
    lapply(., FUN = min) %>%
    unlist() %>%
    unique()

  all_river_joins <- river_to_points %>%
    filter(id %in% joins_selection)

  # Select casted points that are next to each confluence
  close_points <- st_is_within_distance(all_river_joins, river_to_points,
dist = 1)

  # Loop over each points triplet and calculate the distance
  out_dist <- list()
  for (i in 1:length(close_points)){
    out_dist[[i]] <- river_to_points %>%
      filter(id %in% close_points[[i]]) %>%
      st_distance() %>%
      max()
  }

  # Problematic points are extracted
  problematic_points <- close_points[which(out_dist > 0)] %>%
    unlist() %>%
    unique()

  points_out <- river_to_points %>%
    filter(id %in% problematic_points)

  return(points_out)

}

Il giorno mar 14 feb 2023 alle ore 03:05 zhaowentong <
***@***.***> ha scritto:

>
>
>
> See the attachment for a case.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by zhaowentong** [comment]
Hi!This problem has been solved, thank you for your help very much!


















At 2023-02-15 01:25:55, "Damiano Baldan" ***@***.***> wrote:

A function like this should do the job. It will be incorporated in the
tutorial. Best, Damiano

#' Detects gaps in the river network polyline that might cause the function
network_creation to fail
#'
#' @param shape the river network shapefile to be used as input to the
network_creation function
#'
#' @return a point shapefile with the position of the gaps in the river
network
#'
gaps_detection <- function(shape){

# Break shapefile at points
river_to_points <- shape %>%
st_as_sf %>%
st_cast("POINT") %>%
mutate(id = 1:nrow(.))

# Retain all confluences, both good and 'broken' ones
joins_selection <- river_to_points %>%
st_is_within_distance(dist = 0.0001) %>%
Filter(function(x){length(x) > 2 }, .) %>%
lapply(., FUN = min) %>%
unlist() %>%
unique()

all_river_joins <- river_to_points %>%
filter(id %in% joins_selection)

# Select casted points that are next to each confluence
close_points <- st_is_within_distance(all_river_joins, river_to_points,
dist = 1)

# Loop over each points triplet and calculate the distance
out_dist <- list()
for (i in 1:length(close_points)){
out_dist[[i]] <- river_to_points %>%
filter(id %in% close_points[[i]]) %>%
st_distance() %>%
max()
}

# Problematic points are extracted
problematic_points <- close_points[which(out_dist > 0)] %>%
unlist() %>%
unique()

points_out <- river_to_points %>%
filter(id %in% problematic_points)

return(points_out)

}

Il giorno mar 14 feb 2023 alle ore 03:05 zhaowentong <
***@***.***> ha scritto:

>
>
>
> See the attachment for a case.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
