### ISSUE TITLE
index_calculation

### ISSUE THREAD

**Issue by zhaowentong** [damianobaldan/riverconn_tutorial#2]
What should index_type be set to when calculating BFI, it seems that only CCI and RCI types are available.

**Comment by damianobaldan** [comment]
use index_type = "sum" to calculate BFI (equation 2.6 in Baldan et al. 2022 paper). Note that this index was introduced to generalized CAFI and CARFI indices introduced by Jumani et al. (2022), refer to that paper for a more detailed index description. 

Jumani, Suman, et al. "A new index to quantify longitudinal river fragmentation: Conservation and management implications." Ecological Indicators 136 (2022): 108680.
Baldan, Damiano, et al. "Introducing ‘riverconn’: an R package to assess river connectivity indices." Environmental Modelling & Software 156 (2022): 105470.
